0002 basic extractor kaisa kucherenko
yehorlevchenko/h3_audit pull request #17
Opened 2020-09-16 16:08 UTC by kaisa-kucherenko

2020-09-17 17:06 UTC, yehorlevchenko requested changes

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +        forbidden_prefix = ['#', 'tel:', 'mailto:', 'javascript', 'viber:',
Лучше сделать whitelist, т.к. он меньше подвержен изменениям.

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +                if all(not link.startswith(prefix) for prefix in forbidden_prefix):
Нужны будут изменения в связи с появлением whitelist

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +        a = [a for a in unique_a]
list(whatever)

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +                    unique_a.add(tag)
Так получается set объектов супа, а не строк.

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +        result = {'title': title, 'description': description,
Это dict, в котором будут листы с объектами супа, а не листы строк.

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +        result = {'a': a}
Отпадает, см. коммент к 29 строке

2020-09-17 17:06 UTC, yehorlevchenko commented on extractor.py
> +    def worker(self, raw_html):
Названия методов не могут быть существительными, они должны быть глаголами

2020-09-20 15:07 UTC, kaisa-kucherenko commented on extractor.py
> +        pass
добавила dict

2020-09-20 15:08 UTC, kaisa-kucherenko commented on extractor.py
> +        title = [self.soup.title]
+

2020-09-20 15:09 UTC, kaisa-kucherenko commented on extractor.py
> +        result = {'title': title, 'description': description,
изменила принцип формирования результирующего дикта

2020-09-20 15:09 UTC, kaisa-kucherenko commented on extractor.py
> +        result.update(self._extract_a())
сделала

2020-09-20 15:09 UTC, kaisa-kucherenko commented on extractor.py
> +        forbidden_prefix = ['#', 'tel:', 'mailto:', 'javascript', 'viber:',
сделала

2020-09-20 15:09 UTC, kaisa-kucherenko commented on extractor.py
> +                if all(not link.startswith(prefix) for prefix in forbidden_prefix):
внесла изменения

2020-09-20 15:10 UTC, kaisa-kucherenko commented on extractor.py
> +        a = [a for a in unique_a]
:( исправила

2020-09-20 15:10 UTC, kaisa-kucherenko commented on extractor.py
> +                    unique_a.add(tag)
теперь прохожусь по списку объектов супа и использую str(). Нашла такую рекомендацию в доке супа

2020-09-20 15:11 UTC, kaisa-kucherenko commented on extractor.py
> +        result = {'title': title, 'description': description,
исправила

2020-09-20 15:11 UTC, kaisa-kucherenko commented on extractor.py
> +        result = {'a': a}
исправила

2020-09-20 15:11 UTC, kaisa-kucherenko commented on extractor.py
> +    def worker(self, raw_html):
переименовала

2020-09-28 09:21 UTC, closed without merging