Added description and keyword checks
yehorlevchenko/h3_audit pull request #24
Opened 2020-09-20 16:39 UTC by kaisa-kucherenko

2020-09-21 16:28 UTC, yehorlevchenko requested changes

2020-09-21 16:28 UTC, yehorlevchenko commented on analyzer.py
> +        if len(data[0]) < 30:
Мы не обсуждали эти изменения

2020-09-21 16:28 UTC, yehorlevchenko commented on analyzer.py
> +        elif len(data[0]) > 80:
Мы не обсуждали эти изменения. Такие изменения должны быть отдельным ПРом.

2020-09-21 16:28 UTC, yehorlevchenko commented on analyzer.py
> +    1120-1139 - description errors
На такие проверки нам хватит 10 номеров. Исправь тут и в коде.

2020-09-21 16:28 UTC, yehorlevchenko commented on analyzer.py
> +    1140-1159 - keywords errors
Аналогично

2020-09-23 15:02 UTC, kaisa-kucherenko commented on analyzer.py
> +        if len(data[0]) < 30:
Ок, поняла, что такое исправлять отдельными ПР
вернула как было

2020-09-23 15:03 UTC, kaisa-kucherenko commented on analyzer.py
> +        elif len(data[0]) > 80:
вернула

2020-09-23 15:03 UTC, kaisa-kucherenko commented on analyzer.py
> +    1120-1139 - description errors
исправила

2020-09-23 15:03 UTC, kaisa-kucherenko commented on analyzer.py
> +    1140-1159 - keywords errors
исправила

2020-09-28 09:21 UTC, closed without merging