extractor_improvements_kaisa
yehorlevchenko/h3_audit pull request #75
Opened 2020-10-20 09:24 UTC by kaisa-kucherenko

2020-10-20 17:07 UTC, yehorlevchenko requested changes

2020-10-20 17:07 UTC, yehorlevchenko commented on extractor.py
> +                    if not any((url.startswith('www'), url.startswith('http'), url.startswith('./'))):
url.startswith(('www', 'http', './'))

2020-10-20 17:07 UTC, yehorlevchenko commented on extractor.py
> +                        url = f'{base_url}{url.replace("/", "", 1)}'
url = f'{base_url}{url[1:]}'

2020-10-20 17:07 UTC, yehorlevchenko commented on extractor.py
> +                    elif url.startswith('./'):
До этого момента все было понятно.

2020-10-20 17:07 UTC, yehorlevchenko commented on extractor.py
> +                        pass
КОНТИНЬЮ

2020-10-21 10:31 UTC, kaisa-kucherenko commented on extractor.py
> +                    if not any((url.startswith('www'), url.startswith('http'), url.startswith('./'))):
+
упростила еще больше url.startswith('/')

2020-10-21 10:31 UTC, kaisa-kucherenko commented on extractor.py
> +                        url = f'{base_url}{url.replace("/", "", 1)}'
есть

2020-10-21 10:31 UTC, kaisa-kucherenko commented on extractor.py
> +                    elif url.startswith('./'):
оставила комменты

2020-10-21 10:31 UTC, kaisa-kucherenko commented on extractor.py
> +                        pass
поменяла

2020-10-23 17:12 UTC, merged